# Generated by Django 3.1.7 on 2021-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('maildir', models.CharField(max_length=255)),
                ('quota', models.BigIntegerField()),
                ('local_part', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'mailbox',
                'managed': False,
            },
        ),
    ]
